# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 121)
        MainWindow.setMinimumSize(QtCore.QSize(300, 0))
        MainWindow.setMaximumSize(QtCore.QSize(300, 121))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnValidarCPF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.btnValidarCPF.setFont(font)
        self.btnValidarCPF.setObjectName("btnValidarCPF")
        self.gridLayout.addWidget(self.btnValidarCPF, 0, 3, 1, 1)
        self.btnGerarCPF = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.btnGerarCPF.setFont(font)
        self.btnGerarCPF.setObjectName("btnGerarCPF")
        self.gridLayout.addWidget(self.btnGerarCPF, 1, 3, 1, 1)
        self.mostrarResultado = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.mostrarResultado.setFont(font)
        self.mostrarResultado.setObjectName("mostrarResultado")
        self.gridLayout.addWidget(self.mostrarResultado, 2, 0, 1, 1)
        self.receberCPF = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.receberCPF.setFont(font)
        self.receberCPF.setObjectName("receberCPF")
        self.gridLayout.addWidget(self.receberCPF, 0, 0, 1, 1)
        self.cpfSemEspecial = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.cpfSemEspecial.setFont(font)
        self.cpfSemEspecial.setObjectName("cpfSemEspecial")
        self.gridLayout.addWidget(self.cpfSemEspecial, 1, 0, 1, 1)
        self.btnclear = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(15)
        self.btnclear.setFont(font)
        self.btnclear.setObjectName("btnclear")
        self.gridLayout.addWidget(self.btnclear, 2, 3, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Validador de CPF"))
        self.btnValidarCPF.setText(_translate("MainWindow", "Validar CPF"))
        self.btnGerarCPF.setText(_translate("MainWindow", "Gerar CPF"))
        self.btnclear.setText(_translate("MainWindow", "Clear"))
