# Generated by Django 4.0.3 on 2022-03-10 21:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_contato_mostrar_alter_contato_data_criacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='data_criacao',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 10, 21, 43, 23, 151403, tzinfo=utc)),
        ),
    ]
