# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\musica\file_choices_menu_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileOption(object):
    def setupUi(self, FileOption):
        FileOption.setObjectName("FileOption")
        FileOption.resize(436, 225)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FileOption.sizePolicy().hasHeightForWidth())
        FileOption.setSizePolicy(sizePolicy)
        FileOption.setMaximumSize(QtCore.QSize(436, 225))
        self.centralwidget = QtWidgets.QWidget(FileOption)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnRemoveFile = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnRemoveFile.setFont(font)
        self.btnRemoveFile.setObjectName("btnRemoveFile")
        self.gridLayout.addWidget(self.btnRemoveFile, 3, 0, 1, 1)
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 5, 0, 1, 1)
        self.btnCreateFolders = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnCreateFolders.setFont(font)
        self.btnCreateFolders.setObjectName("btnCreateFolders")
        self.gridLayout.addWidget(self.btnCreateFolders, 1, 0, 1, 1)
        self.btnRemoveAll = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnRemoveAll.setFont(font)
        self.btnRemoveAll.setObjectName("btnRemoveAll")
        self.gridLayout.addWidget(self.btnRemoveAll, 4, 0, 1, 1)
        self.inputFileName = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.inputFileName.setFont(font)
        self.inputFileName.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputFileName.setStyleSheet("")
        self.inputFileName.setAlignment(QtCore.Qt.AlignCenter)
        self.inputFileName.setObjectName("inputFileName")
        self.gridLayout.addWidget(self.inputFileName, 0, 0, 1, 1)
        self.btnAutomatic = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnAutomatic.setFont(font)
        self.btnAutomatic.setObjectName("btnAutomatic")
        self.gridLayout.addWidget(self.btnAutomatic, 2, 0, 1, 1)
        FileOption.setCentralWidget(self.centralwidget)

        self.retranslateUi(FileOption)
        QtCore.QMetaObject.connectSlotsByName(FileOption)

    def retranslateUi(self, FileOption):
        _translate = QtCore.QCoreApplication.translate
        FileOption.setWindowTitle(_translate("FileOption", "File Options"))
        self.btnRemoveFile.setText(_translate("FileOption", "Remove File From Folder"))
        self.btnExit.setText(_translate("FileOption", "Exit"))
        self.btnCreateFolders.setText(_translate("FileOption", "Create Folders"))
        self.btnRemoveAll.setText(_translate("FileOption", "Remove All From Folders and Folders"))
        self.inputFileName.setPlaceholderText(_translate("FileOption", "Copy The Folder Here"))
        self.btnAutomatic.setText(_translate("FileOption", "Automatic Folder Creation"))
