# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\musica\file_picker_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FilePicker(object):
    def setupUi(self, FilePicker):
        FilePicker.setObjectName("FilePicker")
        FilePicker.resize(432, 96)
        FilePicker.setMaximumSize(QtCore.QSize(432, 96))
        self.centralwidget = QtWidgets.QWidget(FilePicker)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnExit.setFont(font)
        self.btnExit.setObjectName("btnExit")
        self.gridLayout.addWidget(self.btnExit, 1, 0, 1, 1)
        self.inputFile = QtWidgets.QLineEdit(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.inputFile.setFont(font)
        self.inputFile.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.inputFile.setStyleSheet("")
        self.inputFile.setAlignment(QtCore.Qt.AlignCenter)
        self.inputFile.setObjectName("inputFile")
        self.gridLayout.addWidget(self.inputFile, 0, 0, 1, 6)
        self.btnBack = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnBack.setFont(font)
        self.btnBack.setObjectName("btnBack")
        self.gridLayout.addWidget(self.btnBack, 1, 3, 1, 1)
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnNext.setFont(font)
        self.btnNext.setObjectName("btnNext")
        self.gridLayout.addWidget(self.btnNext, 1, 4, 1, 1)
        self.btnSearch = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnSearch.setFont(font)
        self.btnSearch.setObjectName("btnSearch")
        self.gridLayout.addWidget(self.btnSearch, 1, 5, 1, 1)
        self.btnMenu = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(18)
        self.btnMenu.setFont(font)
        self.btnMenu.setObjectName("btnMenu")
        self.gridLayout.addWidget(self.btnMenu, 1, 2, 1, 1)
        FilePicker.setCentralWidget(self.centralwidget)

        self.retranslateUi(FilePicker)
        QtCore.QMetaObject.connectSlotsByName(FilePicker)

    def retranslateUi(self, FilePicker):
        _translate = QtCore.QCoreApplication.translate
        FilePicker.setWindowTitle(_translate("FilePicker", "File Picker"))
        self.btnExit.setText(_translate("FilePicker", "Exit"))
        self.inputFile.setPlaceholderText(_translate("FilePicker", "Name Of The File"))
        self.btnBack.setText(_translate("FilePicker", "Back"))
        self.btnNext.setText(_translate("FilePicker", "Next"))
        self.btnSearch.setText(_translate("FilePicker", "Search"))
        self.btnMenu.setText(_translate("FilePicker", "Menu"))
